name: Sign and Upload Package
description: 'Signs native modules with garasign'

inputs: 
    aws_role_arn:
      description: 'AWS role input for drivers-github-tools/gpg-sign@v2'
      required: true
    aws_region_name:
      description: 'AWS region name input for drivers-github-tools/gpg-sign@v2'
      required: true
    aws_secret_id:
      description: 'AWS secret id input for drivers-github-tools/gpg-sign@v2'
      required: true
    npm_package_name:
      description: 'The name for the npm package this repository represents'
      required: true
    dry_run:
      description: 'Should we upload files to the release?'
      required: false
      default: 'true'

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4

    - name: Make signatures directory
      shell: bash
      run: mkdir artifacts

    - name: Load version and package info
      uses: baileympearson/drivers-github-tools/node/get_version_info@add-signing-env-action-for-node


    - name: Set up drivers-github-tools
      uses: mongodb-labs/drivers-github-tools/setup@v2
      with: 
        aws_region_name: ${{ inputs.aws_region_name }}
        aws_role_arn: ${{ inputs.aws_role_arn }}
        aws_secret_id: ${{ inputs.aws_secret_id }}

    - name: Create detached signature
      uses: mongodb-labs/drivers-github-tools/gpg-sign@v2
      with: 
        filenames: 'build-*/*.tar.gz'
      env: 
        RELEASE_ASSETS: artifacts/

    - name: Copy the tarballs to the artifacts directory
      shell: bash
      run: for filename in build-*/*.tar.gz; do cp ${filename} artifacts/; done

    - run: npm pack
      shell: bash

    - name: Create detached signature for module
      uses: mongodb-labs/drivers-github-tools/gpg-sign@v2
      with: 
        filenames: ${{ env.package_file }}
      env: 
        RELEASE_ASSETS: artifacts/

    - name: Display structure of downloaded files
      shell: bash
      run: ls -la artifacts/

    - name: "Upload release artifacts"
      if: ${{ inputs.dry_run == false }}
      run: gh release upload v${{ env.package_version }} artifacts/*.*
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}